name: Greg Fisher
favicon: null
layout_spectrum: 0.8018199345096946
typography_spectrum: 0.08241452532820404
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#68b1e8'
    - '#be5185'
    - '#c0b036'
    - '#1d2025'
    - '#dedfd9'
  brandStrength: 0.5935463337227702
  lightness: 0.1435085004195571
  saturation: 0.8764714489225298
  rhythmicContrast: 0.0018184271175414324
purpose: []
